builders:
  - python
upstream:
  - eduid-userdb
  - eduid-dashboard-amp
  - eduid-signup-amp
  - eduid-api-amp
  - eduid-proofing-amp
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: eduid_am
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se

extra_jobs:
  - name: eduid-am-docker
    builders:
      - docker
    docker_name: eduid/eduid-am
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: null
    upstream:
      - eduid-am
