sudo: required
dist: xenial
language: python
python:
  - "3.7"
before_install:
  - docker pull docker.sunet.se/eduid/redis:latest
  - docker pull docker.sunet.se/eduid/mongodb:latest
  - docker pull docker.sunet.se/library/etcd:v3.3.12
# Have Travis CI start mongodb and redis for us
services:
  - docker
# command to install dependencies
install:
  - pip install -U setuptools
  - python setup.py testing
# command to run tests
script:
  - pip freeze
  - pytest
