sudo: required
dist: xenial
language: python
python:
  - "3.7"
before_install:
  - docker pull docker.sunet.se/eduid/redis:latest
  - docker pull docker.sunet.se/eduid/mongodb:latest
# Have Travis CI start mongodb and redis for us
services:
  - docker
# command to install dependencies
install:
  - pip install -U setuptools mypy
  - python setup.py testing
# command to run tests
script:
  - pip freeze
  - nosetests
  - mypy --ignore-missing-imports eduid_am
